FROM docker.io/redhat/ubi9-minimal:latest

HEALTHCHECK --timeout=10s CMD /bin/true || exit 1

COPY log4j-core-2.14.1.jar /

RUN set -ex && \
    microdnf -y install ruby python3-devel python3 python3-pip nodejs shadow-utils tar gzip && \
    pip3 install --index-url https://pypi.org/simple --no-cache-dir aiohttp==3.7.3 pytest urllib3 botocore six numpy && \
    gem install bundler lockbox:0.6.8 ftpd:0.2.1 && \
    npm install -g --cache /tmp/empty-cache debug chalk commander xmldom@0.4.0 && \
    npm cache clean --force && \
    microdnf -y clean all && \
    rm -rf /var/cache/yum /tmp && \
    curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin && \
    curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

USER nobody
ENTRYPOINT /bin/false
